grafana_version: "2.0.2"
influx_db_url: "{{ 'https' if haproxy_use_ssl else 'http' }}://influx.{{ service_discovery_dns_suffix }}"
mesos_url: "{{ 'https' if haproxy_use_ssl else 'http' }}://mesos.{{ service_discovery_dns_suffix }}"
marathon_url: "{{ 'https' if haproxy_use_ssl else 'http' }}://marathon.{{ service_discovery_dns_suffix }}"
uchiwa_url: "{{ 'https' if haproxy_use_ssl else 'http' }}://status.{{ service_discovery_dns_suffix }}"
mesos_version: "0.22.1"
